services:
  redis:
    container_name: sidekiq-demo-redis
    build: ./docker/redis
    volumes:
      - ./docker/data/redis:/data
    ports:
      - 6379:6379
  mysql:
    container_name: sidekiq-demo-mysql
    restart: always
    build: ./docker/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    platform: linux/x86_64