services:
  app:
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/app:delegated
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3000', '-b', '0.0.0.0']
  redis:
    image: redis:latest
    volumes:
      - ./docker/data/redis:/data
    ports:
      - 6379:6379
  mysql:
    restart: always
    build: ./docker/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    platform: linux/x86_64